### ISSUE TITLE
I get dis erro. PLZ FIXZ IN UPGRADE 

### ISSUE THREAD

**Issue by kolabarn** [ingobeans/Auto-OWL-Watcher#10]
Unable to create cache:
[0604/214409.741:ERROR:service_worker_storage.cc(1945)] Failed to delete the database: Database IO error
[0604/214411.584:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.", source:  (0)
[0604/214418.034:INFO:CONSOLE(4232)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/b182fc95/jsbin/desktop_polymer_enable_wil_icons.vflset/desktop_polymer_enable_wil_icons.js (4232)
[0604/214419.501:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.", source:  (0)
[0604/214419.634:ERROR:quota_database.cc(894)] Could not open the quota database, resetting.
[0604/214419.742:WARNING:leveldb_database.cc(123)] Unable to open C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
[0604/214421.761:WARNING:leveldb_database.cc(123)] Unable to open C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
[0604/214423.785:WARNING:leveldb_database.cc(123)] Unable to open C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
[0604/214424.567:ERROR:quota_database.cc(894)] Could not open the quota database, resetting.
[0604/214425.801:WARNING:leveldb_database.cc(123)]"alid API key" in err: err = "   Unable to open C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\shared_proto_db\metadata/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
[0604/214427.470:ERROR:quota_database.cc(896)] Failed to reset the quota database.

[0604/214427.471:ERROR:quota_database.cc(896)] Failed to reset the quota database.
[0604/214429.492:ERROR:sandbox_origin_database.cc(190)] SandboxOriginDatabase failed at: Init@storage\browser\file_system\sandbox_origin_database.cc:94 with error: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\File System\Origins/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
"" is not a function.
[0604/214429.492:WARNING:sandbox_origin_database.cc(106)] Attempting to repair SandboxOriginDatabase.
[0604/214433.535:WARNING:sandbox_origin_database.cc(140)] Failed to repair SandboxOriginDatabase.
[0604/214435.560:ERROR:sandbox_origin_database.cc(190)] SandboxOriginDatabase failed at: Init@storage\browser\file_system\sandbox_origin_database.cc:94 with error: IO error: C:\Users\lumpmaster\AppData\Local\Google\Chrome\User Data\Default\File System\Origins/LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
[0604/214435.560:WARNING:sandbox_origin_database.cc(106)] Attempting to repair SandboxOriginDatabase.
[0604/214439.595:WARNING:sandbox_origin_database.cc(140)] Failed to repair SandboxOriginDatabase.
[0604/214506.518:INFO:CONSOLE(0)] "Access to XMLHttpRequest at line 15'"

Traceback (most recent call last):
  File "c:\Users\lumpmaster\OneDrive\Desktop\Pro\AutoOWLWATCHER_shit_thing\main.py", line 0, in <module>
    YOUTUBE_API_KEY
  File "C:\Users\lumpmaster\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 723, in run   
    return future.result()
  File "C:\Users\lumpmaster\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\lumpmaster\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\lumpmaster\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by kolabarn** [comment]
I AM MAC RN

**Comment by ingobeans** [comment]
Are you running the script on a Mac?

**Comment by kolabarn** [comment]
THIS NOT SCRIPTED. ITS TRUE !!!!?!?!??!

**Comment by ingobeans** [comment]
huh

**Comment by kolabarn** [comment]
I NEDD HELPIE NOT A FUCKIGN HUHU

**Comment by ingobeans** [comment]
Wow! Are you trolling?

**Comment by kolabarn** [comment]
YOUR MOM IS TROLLING, NOW FIX ERROR

**Comment by kolabarn** [comment]
Oh it fixed now, i think i just needed to not do it on a hackintosh

**Comment by ingobeans** [comment]
Good for you.

**Comment by kolabarn** [comment]
what?

**Comment by ingobeans** [comment]
?
